language: python
python:
  - "3.8"
  - "3.9"

install: 
  - python3 -m pip install --upgrade pip
  - pip3 uninstall wheel -y
  - pip3 install -U wheel
  - pip3 uninstall setuptools -y
  - pip3 install -Iv setuptools==49.6.0 --force-reinstall
  - python3 -m pip install -r requirements.txt


script:
  - pytest