name: Bug Report
description: Report broken or incorrect behavior
labels: unconfirmed bug

body:
  - type: markdown
    attributes:
      value: >
        Thank you for taking the time to fill out a bug.
        If you want real-time support/have a question, consider DMing Space#2587.

        Please note that this form is for bugs only!

  - type: input
    attributes:
      label: Discord Username
      description: Enter your discord username and ID! (https://www.remote.tools/remote-work/how-to-find-discord-id)
      value: | 
        Discord Username:    ID: 
    validations:
      required: true
  
  - type: input
    attributes:
      label: Summary
      description: A simple summary of your bug report
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Feature Type
      description: What type of feature is broken?
      options:
        - Commands
        - Interactions (Buttons, Slash Commands, Dropdown)
        - Other (Database, Voice Channels, Data Parsing)
    validations:
      required: true

  - type: textarea
    attributes:
      label: Reproduction Steps
      description: >
        What you did to make it happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Reproducible Command
      description: >
        Upload a screenshot of the command/interaction you sent and the bot's response if there is one. 

  - type: textarea
    attributes:
      label: Expected Results
      description: >
        What did you expect to happen?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Actual Results
      description: >
        What actually happened?
    validations:
      required: true

  - type: input
    attributes:
      label: Location
      description: >
        Where did you run this command?
        Respond with the server name **and** channel name. 
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Checklist
      description: >
        Let's make sure you've properly done due diligence when reporting this issue!
      options:
        - label: I have searched the open issues for duplicates.
          required: true
        - label: I know that I am authorized to perform that command and looked at the documentation to make sure I have done the command correctly.
          required: true
        - label: I have tried the same command/interaction AGAIN after waiting a bit.
          required: true

  - type: textarea
    attributes:
      label: Additional Context
      description: If there is anything else to say, please do so here.
