name: Feature Request
description: Suggest new ideas for Timmy.
labels: feature request

body:
  - type: markdown
    attributes:
      value: >
        Thank you for taking the time to fill out a feature request.
        If you want real-time support/have a question, consider DMing Space#2587.

        Please note that this form is for feature requests only!

  - type: input
    attributes:
      label: Discord Username
      description: Enter your discord username and ID! (https://www.remote.tools/remote-work/how-to-find-discord-id)
      value: | 
        Discord Username:    ID: 
    validations:
      required: true
  
  - type: input
    attributes:
      label: Summary
      description: A simple summary of your feature request.
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Feature Type
      description: What type of feature are you requesting a change for?
      options:
        - Commands
        - Events (e.g. a task which should be done every X hours)
        - Interactions (e.g. Buttons, Slash Commands, Dropdown)
        - Other (e.g. Database, Voice Channels, Data Parsing)
    validations:
      required: true

  - type: textarea
    attributes:
      label: Current Solution
      description: >
        What is the current solution that you are unhappy with?
    validations:
      required: false

  - type: textarea
    attributes:
      label: Current Issue
      description: >
        What seems to be the issue with the current solution.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Suggested Solution
      description: >
        What would you want the solution to be changed to?
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Checklist
      description: >
        Let's make sure you've properly done due diligence when filling this out!
      options:
        - label: I have searched the open issues for duplicates.
          required: true

  - type: textarea
    attributes:
      label: Additional Context
      description: If there is anything else to say, please do so here.