name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Qodana Scan'
      - uses: JetBrains/qodana-action@v5.0.2
      - uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json