on:
  push:
    branches:    
      - 'main'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Run PyTest
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd Timmy-SchoolSimplified
          source ~/TimmyEnv/bin/activate
          git fetch --all
          git reset --hard origin/main
          pip install --upgrade -r requirements.txt
          pip uninstall discord.py -y
          pip install py-cord==2.0.0b4
          ps -ef | grep python3 | grep -v grep | awk '{print $2}' | xargs kill
          nohup python3 main.py &
