name: Timmy Docker Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    #runs-on: [self-hosted, Linux, X64]
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build & Push Image
        run: |
          docker buildx build --push \
            --tag timmyos.azurecr.io/ss-timmy:latest \
            --platform linux/amd64,linux/arm64 .
