name: SSH & PyTest
on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Run PyTest
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          source ~/timmy/bin/activate
          cd Timmy-SchoolSimplified
          git fetch --all
          git reset --hard origin/main
          pip install --upgrade -r requirements.txt
          pip uninstall discord.py -y
          python3 -m pytest

