name: SSH & PyTest
on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Run PyTest
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.BETA_USERNAME }}
        password: ${{ secrets.BETA_PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd Timmy-SchoolSimplified
          source TimmyEnv/bin/activate
          git fetch --all
          git reset --hard origin/beta
          pip install --upgrade -r requirements.txt
          pip uninstall discord.py -y
          pip uninstall py-cord -y
          pip install py-cord==2.0.0b4
          pytest
