name: SSH & PyTest
on: [pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Run PyTest
      run: |
        python3 -m venv TimmyPyTest
        source ~/TimmyPyTest/bin/activate
        pip install --upgrade -r requirements.txt
        pip uninstall discord.py -y
        python3 -m pytest

